apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: instances.aws.com
spec:
  scope: Cluster
  group: aws.com
  names:
    kind: Instance
    plural: instances
    singular: instance
    shortNames:
      - insts
      - inst
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                instanceId:
                   type: string
                instanceLocation:
                   type: string
                instanceTags:
                  type: string
                instanceState:
                   type: string
      additionalPrinterColumns:
        - name: ID
          type: string
          description: shows respective EC2 instance ID's
          jsonPath: .spec.instanceId
        - name: Location
          type: string
          description: Provide locations were instaces are running
          jsonPath: .spec.instanceLocation
          priority: 1
          format: password
        - name: Tags
          type: string
          description: Shows instance tags
          jsonPath: .spec.instanceTags
        - name: Age
          type: date
          description: shows of age of the specific object upon creation
          jsonPath: .metadata.creationTimestamp
        - name: States
          type: string
          description: Shows of EC2 Instances States i.e., Running Stopped
          jsonPath: .spec.instanceState
